<?php
/**
 * Created by PhpStorm.
 * User: HP
 * Date: 07-Jun-17
 * Time: 7:58 PM
 */

namespace App\Controllers\Admin;


class Notifications extends \Core\Admin {


    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }


    // renders page with all notifications
    public function allUnreadNotifications(){

        $notifications = Notification::getAllUnreadNotifications();

    }

}