<?php
/**
 * Created by PhpStorm.
 * User: HP
 * Date: 24-Jun-17
 * Time: 2:21 PM
 */

namespace App\Controllers;


use Core\View;

class Rooms extends \Core\Controller {

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }


    public function searchResultsAction(){

        $checkin  = $_POST['checkin'] ?? false;
        $checkout = $_POST['checkout'] ?? false;

        View::renderTemplate('rooms/search_results.html', [
            'rooms'    => 0,
            'checkin'  => $checkin,
            'checkout' => $checkout
        ]);
    }
}